# This configuration file is used to map joystick inputs to control the movement of a robot 
# using the 'joy_teleop' node. It translates joystick axes into velocity commands.
# publishe it in bumperbot_controller/cmd_vel topic where the controller listining.


joy_teleop:
  ros__parameters:
    move:
      type: topic  # Type of output, here it's a ROS topic.
      interface_type: geometry_msgs/msg/TwistStamped  # Message type used for sending velocity commands.
      topic_name: bumperbot_controller/cmd_vel  # Topic name where velocity commands are published.
      deadman_buttons: [5]  # List of buttons that must be held to enable joystick input.
      axis_mappings:
        twist-linear-x:
          axis: 1  # Joystick axis for linear movement (forward/backward).
          scale: 1.0  # Scale factor for linear velocity.
          offset: 0.0  # Offset applied to the linear velocity.
        twist-angular-z:
          axis: 3  # Joystick axis for angular movement (rotation).
          scale: 8.0  # Scale factor for rotational speed.
          offset: 0.0  # Offset applied to the angular velocity.
