# Configuration file for the joystick input in a ROS2-based robot.
joystick:
  ros__parameters:
    # The ID of the joystick device. 
    # If using only one joystick, this is typically set to 0.
    device_id: 0

    # The name of the joystick device. 
    # Leave it empty to use the default or first detected joystick.
    device_name: ""

    # The deadzone value helps to ignore small unintentional movements or noise from the joystick.
    # This value is between 0 and 1, where 0.5 means that 50% of small movements around the joystick's center will be ignored.
    deadzone: 0.5

    # The rate (in Hz) at which the joystick input is repeated when a button is held down.
    # For example, a value of 20.0 means that a button press will be repeated 20 times per second.
    autorepeat_rate: 20.0

    # If set to true, buttons will remain in the pressed state until they are pressed again.
    # This can be useful for certain types of control, but is set to false here for standard behavior.
    sticky_buttons: false

    # This parameter specifies the interval (in milliseconds) to coalesce events.
    # It helps in reducing the number of published events to the ROS2 system, useful for reducing data frequency.
    # Here, it is set to 1ms for minimal delay between events.
    coalesce_interval_ms: 1
